#!/usr/bin/env bash
# =============================================================================
# start-compose.sh — Alephant Docker Compose 部署脚本
# 使用方式:
#   cd alephant-docker/ && bash start-compose.sh
#
# 目录结构:
#   compose/   — docker-compose.yml + env 文件 + config/
#   sql/       — 共享 SQL（pgsql + clickhouse）
#
# 脚本自动完成:
# 1. 生成随机密码和密钥
# 2. 填充 compose/*.env 文件
# 3. 交互式收集 License 信息（邮箱 + license.jwt）
# 4. 启动 compose 栈 + 初始化数据库
# =============================================================================
set -euo pipefail

COMPOSE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_PROJECT_DIR="${COMPOSE_DIR}/compose"
SQL_DIR="${COMPOSE_DIR}/sql"

# 颜色
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }

# ─── 密码/密钥生成 ──────────────────────────────────────────────────────────
gen_pswd() { openssl rand -base64 32 | tr -d '/+=' | cut -c1-24; }
gen_jwt()  { openssl rand -base64 48 | tr -d '/+='; }
gen_key()  { openssl rand -base64 32; }
gen_token(){ openssl rand -base64 32; }
gen_stripe(){ echo "sk_test_$(openssl rand -hex 32)"; }

# ─── 基础设施配置 ───────────────────────────────────────────────────────────
load_or_generate_infra_config() {
  if [[ -f "${COMPOSE_PROJECT_DIR}/infra.env" ]]; then
    info "复用已有 infra.env 中的基础设施凭证"
    # infra.env is generated by this script and contains shell-safe values.
    # shellcheck disable=SC1091
    source "${COMPOSE_PROJECT_DIR}/infra.env"
    # 兼容旧版 infra.env（缺少部分变量）
    POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-"$(gen_pswd)"}"
    CLICKHOUSE_PASSWORD="${CLICKHOUSE_PASSWORD:-"$(gen_pswd)"}"
    VALKEY_PASSWORD="${VALKEY_PASSWORD:-"$(gen_pswd)"}"
    QDRANT_API_KEY="${QDRANT_API_KEY:-"$(gen_key)"}"
    MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
    MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-"$(gen_pswd)"}"
    return
  fi

  info "首次部署，生成基础设施凭证"
  POSTGRES_DB=alephant
  POSTGRES_USER=alephant
  POSTGRES_PASSWORD=$(gen_pswd)
  CLICKHOUSE_DB=alephant
  CLICKHOUSE_USER=default
  CLICKHOUSE_PASSWORD=$(gen_pswd)
  VALKEY_PASSWORD=$(gen_pswd)
  QDRANT_API_KEY=$(gen_token)
  MINIO_ROOT_USER=minioadmin
  MINIO_ROOT_PASSWORD=$(gen_pswd)

  cat > "${COMPOSE_PROJECT_DIR}/infra.env" << EOF
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
CLICKHOUSE_DB=${CLICKHOUSE_DB}
CLICKHOUSE_USER=${CLICKHOUSE_USER}
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
VALKEY_PASSWORD=${VALKEY_PASSWORD}
QDRANT_API_KEY=${QDRANT_API_KEY}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
EOF
}

# ─── 前置检查 ────────────────────────────────────────────────────────────────
check_prereqs() {
  local FAIL=0
  command -v docker &>/dev/null || { err "Docker 未安装"; FAIL=1; }
  docker info &>/dev/null      || { err "Docker daemon 未运行"; FAIL=1; }
  command -v openssl &>/dev/null || { err "需要 openssl"; FAIL=1; }
  command -v curl &>/dev/null || command -v wget &>/dev/null || { err "需要 curl 或 wget"; FAIL=1; }
  [ -f "${COMPOSE_PROJECT_DIR}/docker-compose.yml" ] || { err "缺少 docker-compose.yml"; FAIL=1; }
  [ "$FAIL" = "1" ] && exit 1
  ok "前置检查通过"
}

# ─── 从 API 拉取最新镜像标签 ──────────────────────────────────────────────
fetch_latest_tags() {
  info "获取最新镜像标签..."
  local API_URL="https://image-versions.alephant.io/alephant/images/latest"
  local RESPONSE=""

  if command -v curl &>/dev/null; then
    RESPONSE=$(curl -sf --connect-timeout 5 "$API_URL" 2>/dev/null || true)
  elif command -v wget &>/dev/null; then
    RESPONSE=$(wget -qO- --timeout=5 "$API_URL" 2>/dev/null || true)
  fi

  if [ -z "$RESPONSE" ]; then
    warn "无法获取最新镜像标签，将使用 docker-compose.yml 中的默认值"
    return
  fi

  # API 返回完整镜像 URL: "saas-app": "registry.openmodels.link/alephant/alephant-app:20260713224933"
  local APP_IMAGE_VAL SAAS_SERVICE_IMAGE_VAL POLICY_SERVICE_IMAGE_VAL AI_GATEWAY_IMAGE_VAL LOGS_COLLECTOR_IMAGE_VAL

  APP_IMAGE_VAL=$(echo "$RESPONSE" | grep -o '"saas-app": *"[^"]*"' | cut -d'"' -f4 || true)
  SAAS_SERVICE_IMAGE_VAL=$(echo "$RESPONSE" | grep -o '"saas-service": *"[^"]*"' | cut -d'"' -f4 || true)
  POLICY_SERVICE_IMAGE_VAL=$(echo "$RESPONSE" | grep -o '"policy-service": *"[^"]*"' | cut -d'"' -f4 || true)
  AI_GATEWAY_IMAGE_VAL=$(echo "$RESPONSE" | grep -o '"ai-gateway": *"[^"]*"' | cut -d'"' -f4 || true)
  LOGS_COLLECTOR_IMAGE_VAL=$(echo "$RESPONSE" | grep -o '"logs-collector": *"[^"]*"' | cut -d'"' -f4 || true)

  # 导出完整镜像 URL — compose 文件中的 ${VAR:-default} 会自动使用
  if [ -n "$APP_IMAGE_VAL" ]; then
    export APP_IMAGE="${APP_IMAGE_VAL}"
  else
    warn "saas-app 标签获取失败，使用默认值"
  fi
  if [ -n "$SAAS_SERVICE_IMAGE_VAL" ]; then
    export SAAS_SERVICE_IMAGE="${SAAS_SERVICE_IMAGE_VAL}"
  else
    warn "saas-service 标签获取失败，使用默认值"
  fi
  if [ -n "$POLICY_SERVICE_IMAGE_VAL" ]; then
    export POLICY_SERVICE_IMAGE="${POLICY_SERVICE_IMAGE_VAL}"
  else
    warn "policy-service 标签获取失败，使用默认值"
  fi
  if [ -n "$AI_GATEWAY_IMAGE_VAL" ]; then
    export AI_GATEWAY_IMAGE="${AI_GATEWAY_IMAGE_VAL}"
  else
    warn "ai-gateway 标签获取失败，使用默认值"
  fi
  if [ -n "$LOGS_COLLECTOR_IMAGE_VAL" ]; then
    export LOGS_COLLECTOR_IMAGE="${LOGS_COLLECTOR_IMAGE_VAL}"
  else
    warn "logs-collector 标签获取失败，使用默认值"
  fi

  # 提取 tag 仅用于展示
  local TAG
  TAG="${APP_IMAGE_VAL##*:}"
  ok "镜像已更新: ${APP_IMAGE_VAL:-默认}"
  [ -n "$SAAS_SERVICE_IMAGE_VAL" ] && ok "          ${SAAS_SERVICE_IMAGE_VAL}"
  [ -n "$POLICY_SERVICE_IMAGE_VAL" ] && ok "          ${POLICY_SERVICE_IMAGE_VAL}"
  [ -n "$AI_GATEWAY_IMAGE_VAL" ] && ok "          ${AI_GATEWAY_IMAGE_VAL}"
  [ -n "$LOGS_COLLECTOR_IMAGE_VAL" ] && ok "          ${LOGS_COLLECTOR_IMAGE_VAL}"
}

# ─── 生成所有环境变量文件 ──────────────────────────────────────────────────
generate_config() {
  info "生成随机密码和密钥..."

  # ── infra 密码 ──
  # PostgreSQL stores its password in the persistent data volume and does not
  # apply POSTGRES_PASSWORD again after the first initialization. Reusing the
  # existing infra.env keeps all dependent service URLs aligned with it.
  load_or_generate_infra_config

  # ── 共享密钥 ──
  JWT_SECRET=$(gen_jwt)
  MASTER_KEY=$(gen_jwt)
  ENCRYPTION_KEY=$(gen_key)
  MASTER_KEY_ENCRYPTION_KEY=$(gen_key)
  NOTIFICATION_ENCRYPTION_KEY=$(gen_key)
  LOGS_COLLECTOR_X402_HTTP_AUTH_TOKEN=$(gen_token)
  PAYMENT_SERVICE_KEY=$(gen_token)
  OUTBOUND_PAYMENT_HMAC_SECRET=$(gen_jwt)
  REVENUE_WITHDRAW_HMAC_SECRET=$(gen_jwt)
  S3_ACCESS_KEY=${MINIO_ROOT_USER}
  S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
  MAIL_PASSWORD=""
  STRIPE_SECRET_KEY=""
  OAUTH_GITHUB_CLIENT_SECRET=""
  OAUTH_GOOGLE_CLIENT_SECRET=""
  PAYMENT_LEDGER_INTERNAL_TOKEN=""
  X402_SELF_HOSTED_AUTH_TOKEN=""
  PAYMENT_INTERNAL_AUTH_TOKEN=""

  # ── 1. infra.env ──
  info "  生成 infra.env"
  cat > "${COMPOSE_PROJECT_DIR}/infra.env" << EOF
POSTGRES_DB=alephant
POSTGRES_USER=alephant
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
CLICKHOUSE_DB=alephant
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
VALKEY_PASSWORD=${VALKEY_PASSWORD}
QDRANT_API_KEY=${QDRANT_API_KEY}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
EOF

  # ── 2. .env (compose 变量插值用) ──
  info "  生成 .env"
  cat > "${COMPOSE_PROJECT_DIR}/.env" << EOF
POSTGRES_USER=alephant
POSTGRES_DB=alephant
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
VALKEY_PASSWORD=${VALKEY_PASSWORD}
QDRANT_API_KEY=${QDRANT_API_KEY}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
EOF

  # ── 3. saas-service.env ──
  info "  生成 saas-service.env"
  cat > "${COMPOSE_PROJECT_DIR}/saas-service.env" << EOF
# ===========================================================================
# saas-service.env — 由 start.sh 自动生成
# ===========================================================================
POSTGRES_DATABASE_URL=postgresql://alephant:${POSTGRES_PASSWORD}@postgres:5432/alephant
REDIS_URL=redis://default:${VALKEY_PASSWORD}@valkey:6379/0
APP_BASE_URL=http://localhost
MASTER_KEY=${MASTER_KEY}
MASTER_KEY_ENCRYPTION_KEY=${MASTER_KEY_ENCRYPTION_KEY}
JWT_SECRET=${JWT_SECRET}
ENABLE_SWAGGER_UI=true
JWT_ACCESS_TTL=900
JWT_REFRESH_TTL=604800
CSRF_TOKEN_TTL=86400
REDIS_KEY_PREFIX=
REDIS_LOCK_DEFAULT_TTL_SECONDS=30
REDIS_LOCK_RENEW_INTERVAL_SECONDS=10
REDIS_STRONG_COORDINATION=true
IDEMPOTENCY_TTL_SECONDS=86400
LAST_USED_DEBOUNCE_SECONDS=5
APP_BASE_URL=http://localhost
ENV=development
REFRESH_COOKIE_NAME=refresh_token
REFRESH_COOKIE_HTTP_ONLY=true
REFRESH_COOKIE_SAME_SITE=lax
REFRESH_COOKIE_SECURE=false
ENFORCE_TRIAL_ONCE_PER_USER=false
AUTH_RATE_LIMIT_PER_MIN=60
SALES_LEAD_EMAIL=admin@example.com


# OAuth (placeholder)
OAUTH_GITHUB_CLIENT_ID=
OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
OAUTH_GITHUB_ALLOWED_REDIRECT_URIS=http://localhost:8081/auth/github/callback
OAUTH_GOOGLE_CLIENT_ID=
OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}

# Mail (placeholder)
MAIL_HOST=
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=${MAIL_PASSWORD}
MAIL_FROM_ADDRESS=noreply@example.com
MAIL_FROM_NAME=Alephant

# Payment
PAYMENT_SERVICE_BASE_URL=http://ledge-service:8080
PAYMENT_SERVICE_KEY=${PAYMENT_SERVICE_KEY}
PAYMENT_LEDGER_GRPC_ADDR=ledge-service:9090
PAYMENT_LEDGER_INTERNAL_TOKEN=${PAYMENT_LEDGER_INTERNAL_TOKEN}

# Policy / Notification
NOTIFICATION_ENCRYPTION_KEY=${NOTIFICATION_ENCRYPTION_KEY}

# HMAC
OUTBOUND_PAYMENT_HMAC_SECRET=${OUTBOUND_PAYMENT_HMAC_SECRET}
REVENUE_WITHDRAW_HMAC_SECRET=${REVENUE_WITHDRAW_HMAC_SECRET}

# Logs
COLLECTOR_ANALYTICS_BASE_URL=http://logs-collector:8585
LOGS_COLLECTOR_X402_HTTP_AUTH_TOKEN=${LOGS_COLLECTOR_X402_HTTP_AUTH_TOKEN}
EOF

  # ── 4. policy-service.env ──
  info "  生成 policy-service.env"
  cat > "${COMPOSE_PROJECT_DIR}/policy-service.env" << EOF
POSTGRES_DATABASE_URL=postgresql://alephant:${POSTGRES_PASSWORD}@postgres:5432/alephant
REDIS_URL=redis://default:${VALKEY_PASSWORD}@valkey:6379/0
MAIL_HOST=
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=${MAIL_PASSWORD}
MAIL_FROM_ADDRESS=noreply@example.com
MAIL_FROM_NAME=Alephant
POLICY_CONFIG_STREAM=alephant-policy
POLICY_NOTIFY_CHANNEL=alephant-notify
POLICY_USE_STREAM=true
POLICY_STREAM_BATCH_SIZE=100
POLICY_STREAM_BLOCK_MS=1000
POLICY_STREAM_CONSUMER_GROUP=policy-consumer
POLICY_STREAM_CONSUMER_NAME=policy-node-0
POLICY_BOOTSTRAP_REFRESH=true
POLICY_BOOTSTRAP_REFRESH_CONCURRENCY=10
POLICY_BOOTSTRAP_REFRESH_TIMEOUT_SEC=30
ENDPOINT_POLICY_CONFIG_STREAM=alephant-policy
WATCHER_ENABLED=true
NOTIFICATION_ENCRYPTION_KEY=${NOTIFICATION_ENCRYPTION_KEY}
NOTIFICATION_OUTBOX_NOTIFY_CHANNEL=alephant-notification
LOG_LEVEL=info
EOF

  # ── 5. ai-gateway.env ──
  info "  生成 ai-gateway.env"
  cat > "${COMPOSE_PROJECT_DIR}/ai-gateway.env" << EOF
POSTGRES_DATABASE_URL=postgresql://alephant:${POSTGRES_PASSWORD}@postgres:5432/alephant
REDIS_URL=redis://default:${VALKEY_PASSWORD}@valkey:6379/0
CLICKHOUSE_CREDS={"CLICKHOUSE_HOST":"http://clickhouse:8123","CLICKHOUSE_USER":"default","CLICKHOUSE_PASSWORD":"${CLICKHOUSE_PASSWORD}","CLICKHOUSE_HQL_USER":"hql_user","CLICKHOUSE_HQL_PASSWORD":""}
AI_GATEWAY__SEMANTIC_CACHE__QDRANT__URL=http://qdrant:6333
AI_GATEWAY__SEMANTIC_CACHE__QDRANT__API_KEY=${QDRANT_API_KEY}
AI_GATEWAY__TIKV_KV__PD_ENDPOINTS=["pd:2379"]
AI_GATEWAY__TIKV_KV__CA_CERT_PATH=
AI_GATEWAY__POLICY__GRPC_ENDPOINT=policy-service:9090
AI_GATEWAY__X402__PAYMENT_GRPC_ENDPOINT=
AI_GATEWAY__X402__UPSTREAM_AUTH_KEY=
AI_GATEWAY__ALEPHANT__LOG_COLLECTOR_URL=http://logs-collector:8585
AI_GATEWAY__REQUEST_LOG__TRANSPORT=http
S3_ENDPOINT=http://minio:9000
S3_REGION=us-east-1
S3_BUCKET_NAME=alephant
S3_ACCESS_KEY=${S3_ACCESS_KEY}
S3_SECRET_KEY=${S3_SECRET_KEY}
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
MASTER_KEY_ENCRYPTION_KEY=${MASTER_KEY_ENCRYPTION_KEY}
PAYMENT_SERVICE_KEY=${PAYMENT_SERVICE_KEY}
LOGS_COLLECTOR_X402_HTTP_AUTH_TOKEN=${LOGS_COLLECTOR_X402_HTTP_AUTH_TOKEN}
KEY_MARKET_API_KEY_HASH_SECRET=${MASTER_KEY_ENCRYPTION_KEY}
ANALYTICS_RMT_MAX_RANGE_HOURS=24000
EOF

  # ── 6. logs-collector.env ──
  info "  生成 logs-collector.env"
  cat > "${COMPOSE_PROJECT_DIR}/logs-collector.env" << EOF
POSTGRES_DATABASE_URL=postgresql://alephant:${POSTGRES_PASSWORD}@postgres:5432/alephant
REDIS_URL=redis://default:${VALKEY_PASSWORD}@valkey:6379/0
CLICKHOUSE_CREDS={"CLICKHOUSE_HOST":"http://clickhouse:8123","CLICKHOUSE_USER":"default","CLICKHOUSE_PASSWORD":"${CLICKHOUSE_PASSWORD}","CLICKHOUSE_HQL_USER":"hql_user","CLICKHOUSE_HQL_PASSWORD":""}
S3_ENDPOINT=http://minio:9000
S3_REGION=us-east-1
S3_BUCKET_NAME=alephant
S3_ACCESS_KEY=${S3_ACCESS_KEY}
S3_SECRET_KEY=${S3_SECRET_KEY}
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
LOGS_COLLECTOR_X402_HTTP_AUTH_TOKEN=${LOGS_COLLECTOR_X402_HTTP_AUTH_TOKEN}
ANALYTICS_RMT_MAX_RANGE_HOURS=72
EOF

  # ── 7. app.env (给 saas-app 的环境变量，SPA 可通过 _env 接口读取) ──
  info "  生成 app.env"
  cat > "${COMPOSE_PROJECT_DIR}/app.env" << EOF
# ===========================================================================
# app.env — 由 start.sh 自动生成
# SPA 前端通过 GET /_env 获取 API_BASE_URL 和 COLLECTOR_BASE_URL
# 生产部署时应根据实际域名修改:
#   API_BASE_URL      = https://your-domain.com
#   COLLECTOR_BASE_URL = https://analytics.your-domain.com
# ===========================================================================
API_BASE_URL=${API_BASE_URL:-http://localhost}
GATEWAY_BASE_URL=${GATEWAY_BASE_URL:-http://localhost:81/v1}
COLLECTOR_BASE_URL=${COLLECTOR_BASE_URL:-http://localhost:82}
EOF

  ok "环境变量文件已生成"
  info "  PostgreSQL 密码: ${POSTGRES_PASSWORD}"
  info "  Valkey 密码:     ${VALKEY_PASSWORD}"
  info "  JWT 密钥:        ${JWT_SECRET}"
}

# ─── License 激活信息收集 ────────────────────────────────────────────────
collect_license() {
  echo ""
  echo "═══════════════════════════════════════════"
  echo "  License 激活"
  echo "═══════════════════════════════════════════"
  echo ""

  # ── 1. 工作空间拥有者邮箱 ──
  while [ -z "${PRIVATE_WORKSPACE_OWNER_EMAILS:-}" ]; do
    read -r -p "  请输入工作空间拥有者邮箱 (多个用逗号分隔): " PRIVATE_WORKSPACE_OWNER_EMAILS
    [ -z "${PRIVATE_WORKSPACE_OWNER_EMAILS}" ] && warn "邮箱不能为空，请重新输入"
  done

  # ── 2. license.jwt ──
  local LICENSE_DIR="${COMPOSE_PROJECT_DIR}/license"
  mkdir -p "${LICENSE_DIR}"

  if [ -f "${LICENSE_DIR}/license.jwt" ] && [ -s "${LICENSE_DIR}/license.jwt" ]; then
    # 已有文件，询问是否覆盖
    local OVERWRITE
    read -r -p "  license/license.jwt 已存在，是否覆盖? (y/N): " OVERWRITE
    if [[ ! "${OVERWRITE}" =~ ^[Yy]$ ]]; then
      ok "保留已有 license.jwt"
    else
      write_license_file "${LICENSE_DIR}"
    fi
  else
    write_license_file "${LICENSE_DIR}"
  fi

  # ── 写入 .env ──
  echo "PRIVATE_WORKSPACE_OWNER_EMAILS=${PRIVATE_WORKSPACE_OWNER_EMAILS}" >> "${COMPOSE_PROJECT_DIR}/.env"
  ok "PRIVATE_WORKSPACE_OWNER_EMAILS 已写入 .env"

  echo ""
  ok "License 配置完成"
}

write_license_file() {
  local dir="$1"
  echo ""
  echo "  请将从 Alephant 团队获取的 JWT 内容粘贴到下方，"
  echo "  粘贴完成后按 Ctrl+D (EOF) 结束:"
  echo ""
  local content
  content=$(cat) || true
  if [ -n "${content}" ]; then
    echo "${content}" > "${dir}/license.jwt"
    ok "license.jwt 已写入 (${#content} 字符)"
  else
    warn "内容为空，跳过 license.jwt 写入"
  fi
}

# ─── 数据库初始化 ──────────────────────────────────────────────────────────
init_databases() {
  info "初始化数据库..."

  # ── 等待 PostgreSQL 就绪 ──
  info "  等待 PostgreSQL 就绪..."
  local RETRIES=30
  local WAIT=2
  local i=0
  while [ $i -lt $RETRIES ]; do
    if docker compose exec -T postgres pg_isready -U alephant &>/dev/null; then
      ok "  PostgreSQL 就绪"
      break
    fi
    i=$((i + 1))
    sleep $WAIT
  done
  if [ $i -ge $RETRIES ]; then
    err "PostgreSQL 未能就绪，跳过初始化"
    return 1
  fi

  # ── 检查是否已有表 ──
  local TABLE_COUNT
  TABLE_COUNT=$(docker compose exec -T postgres psql -U alephant -d alephant -t -c "SELECT count(*) FROM information_schema.tables WHERE table_schema='public';" 2>/dev/null | tr -d ' ')
  if [ -n "${TABLE_COUNT}" ] && [ "${TABLE_COUNT}" -gt 0 ] 2>/dev/null; then
    ok "  数据库已有 ${TABLE_COUNT} 张表，跳过初始化"
  else
    info "  导入 pgsql.sql..."
    docker compose exec -T postgres psql -U alephant -d alephant < "${SQL_DIR}/pgsql.sql" 2>&1 | grep -E "ERROR|CREATE TABLE|INSERT" || true
    ok "  pgsql.sql 导入完成"
  fi

  # ── 等待 ClickHouse 就绪 ──
  info "  等待 ClickHouse 就绪..."
  i=0
  while [ $i -lt $RETRIES ]; do
    if docker compose exec -T clickhouse clickhouse-client --user default --password "${CLICKHOUSE_PASSWORD}" --query "SELECT 1" &>/dev/null; then
      ok "  ClickHouse 就绪"
      break
    fi
    i=$((i + 1))
    sleep $WAIT
  done
  if [ $i -ge $RETRIES ]; then
    warn "ClickHouse 未能就绪，跳过初始化"
    return
  fi

  # ── ClickHouse 初始化（容忍已知的 Dictionary 引擎错误） ──
  local CH_TABLES
  CH_TABLES=$(docker compose exec -T clickhouse clickhouse-client --user default --password "${CLICKHOUSE_PASSWORD}" --query "SHOW TABLES" 2>/dev/null | wc -l | tr -d ' ')
  if [ -n "${CH_TABLES}" ] && [ "${CH_TABLES}" -gt 0 ] 2>/dev/null; then
    ok "  ClickHouse 已有 ${CH_TABLES} 张表，跳过初始化"
  else
    info "  导入 clickhouse.sql..."
    # 已知 Dictionary 引擎表创建会报错，忽略该错误
    docker compose exec -T clickhouse clickhouse-client --user default --password "${CLICKHOUSE_PASSWORD}" < "${SQL_DIR}/clickhouse.sql" 2>&1 | grep -v "DB::Exception" || true
    ok "  clickhouse.sql 导入完成"
  fi
}

# ─── 启动服务 ──────────────────────────────────────────────────────────────
start_services() {
  info "启动所有服务..."
  cd "${COMPOSE_PROJECT_DIR}"
  docker compose up -d 2>&1
  ok "服务已启动!"
  echo ""
  echo "  查看状态: docker compose ps"
  echo "  查看日志: docker compose logs -f"
}

# ─── 主流程 ──────────────────────────────────────────────────────────────
main() {
  echo ""
  echo "═══════════════════════════════════════════"
  echo "  Alephant 一键部署"
  echo "═══════════════════════════════════════════"
  echo ""

  check_prereqs
  generate_config
  collect_license
  fetch_latest_tags
  start_services
  init_databases

  echo ""
  echo "═══════════════════════════════════════════"
  echo "  ✅ 部署完成"
  echo "═══════════════════════════════════════════"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
